### ISSUE TITLE
Win32 compile error 

### ISSUE THREAD

**Issue by sgf** [aharabada/directx-beef#1]
Compiling...
Beef compilation time: 1.93s
WARNING: BF0162: Unreachable code at line 314:4 in d:\App\Beef\BeefLibs\corlib\src\Collections\Dictionary.bf
   if (sizeof(int_cosize) == 8)
   ^
737 modules built, 737 object files generated
Errors: 0. Warnings: 1.
Executing: D:\App\VS\2022E\VC\Tools\MSVC\14.30.30705\bin\Hostx86\x86/link.exe @C:\Users\super\AppData\Local\Temp\tmpFCDB.tmp
DirectX_Common_HResult.obj : error LNK2019: unresolved external symbol _FormatMessageW referenced in function "public: static void __cdecl bf::DirectX::Common::HResult::ToString__im(int,class bf::System::String *)" (?ToString__im@HResult@Common@DirectX@bf@@SAXHPAVString@System@4@@Z)
DirectX_Windows_Kernel32_GLOBALS_.obj : error LNK2001: unresolved external symbol _FormatMessageW
DirectX_Windows_Winuser_GLOBALS_.obj : error LNK2019: unresolved external symbol _SetWindowLongPtrW@12 referenced in function _FORCELINK_SetWindowLongPtrW
SimpleTriangleExample_Window.obj : error LNK2001: unresolved external symbol _SetWindowLongPtrW@12
DirectX_Windows_Winuser_GLOBALS_.obj : error LNK2019: unresolved external symbol _GetWindowLongPtrW@8 referenced in function _FORCELINK_GetWindowLongPtrW
SimpleTriangleExample_Window.obj : error LNK2001: unresolved external symbol _GetWindowLongPtrW@8
d:\3rdSrc\Beef\directx-beef\Examples\D3D11\SimpleTriangleExample\build\Debug_Win32\SimpleTriangleExample\SimpleTriangleExample.exe : fatal error LNK1120: 3 unresolved externals
Execution time: 0.79s
Execution Failed
ERROR: BUILD FAILED
Total build time: 2.82s

**Comment by aharabada** [comment]
Until now I actually never tried to build the library for 32-bits.

Should be fixed at 4c7ff2e88691a705f75ea755781dbce8a4454c66

**Comment by sgf** [comment]
> 

Compiling...
Beef compilation time: 0.15s
ERROR: Expected type at line 14:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DBlob.bf
   public function [CallingConvention(.Stdcall)] void*(ID3DBlob *self) GetBufferPointer;
                   ^
ERROR: Method return type expected at line 14:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DBlob.bf
   public function [CallingConvention(.Stdcall)] void*(ID3DBlob *self) GetBufferPointer;
                                                 ^^^^^
ERROR: Expected method body at line 14:71 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DBlob.bf
   public function [CallingConvention(.Stdcall)] void*(ID3DBlob *self) GetBufferPointer;
                                                                      ^
ERROR: Member name expected at line 14:88 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DBlob.bf
   public function [CallingConvention(.Stdcall)] void*(ID3DBlob *self) GetBufferPointer;
                                                                                       ^
ERROR: Expected type at line 15:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DBlob.bf
   public function [CallingConvention(.Stdcall)] SIZE_T(ID3DBlob *self) GetBufferSize; 
                   ^
ERROR: Method return type expected at line 15:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DBlob.bf
   public function [CallingConvention(.Stdcall)] SIZE_T(ID3DBlob *self) GetBufferSize; 
                                                 ^^^^^^
ERROR: Expected method body at line 15:72 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DBlob.bf
   public function [CallingConvention(.Stdcall)] SIZE_T(ID3DBlob *self) GetBufferSize; 
                                                                       ^
ERROR: Member name expected at line 15:86 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DBlob.bf
   public function [CallingConvention(.Stdcall)] SIZE_T(ID3DBlob *self) GetBufferSize; 
                                                                                     ^
ERROR: Expected type at line 28:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DInclude.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3DInclude* self, IncludeType includeType, /*LPCSTR*/ char8 *pFileName, /*LPCVOID*/ void *pParentData, /*LPCVOID*/ void **ppData, uint32 *pBytes) Open;
                   ^
ERROR: Method return type expected at line 28:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DInclude.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3DInclude* self, IncludeType includeType, /*LPCSTR*/ char8 *pFileName, /*LPCVOID*/ void *pParentData, /*LPCVOID*/ void **ppData, uint32 *pBytes) Open;
                                                 ^^^^^^^
ERROR: Expected method body at line 28:204 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DInclude.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3DInclude* self, IncludeType includeType, /*LPCSTR*/ char8 *pFileName, /*LPCVOID*/ void *pParentData, /*LPCVOID*/ void **ppData, uint32 *pBytes) Open;
                                                                                                                                                                                                           ^
ERROR: Member name expected at line 28:209 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DInclude.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3DInclude* self, IncludeType includeType, /*LPCSTR*/ char8 *pFileName, /*LPCVOID*/ void *pParentData, /*LPCVOID*/ void **ppData, uint32 *pBytes) Open;
                                                                                                                                                                                                                ^
ERROR: Expected type at line 40:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DInclude.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3DInclude* self, /*LPCVOID*/ void **ppData) Close;
                   ^
ERROR: Method return type expected at line 40:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DInclude.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3DInclude* self, /*LPCVOID*/ void **ppData) Close;
                                                 ^^^^^^^
ERROR: Expected method body at line 40:103 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DInclude.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3DInclude* self, /*LPCVOID*/ void **ppData) Close;
                                                                                                      ^
ERROR: Member name expected at line 40:109 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\ID3DInclude.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3DInclude* self, /*LPCVOID*/ void **ppData) Close;
                                                                                                            ^
ERROR: Expected type at line 22:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] HResult(IUnknown* self, ref Guid riid, void** result) QueryInterface;
                   ^
ERROR: Method return type expected at line 22:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] HResult(IUnknown* self, ref Guid riid, void** result) QueryInterface;
                                                 ^^^^^^^
ERROR: Expected method body at line 22:103 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] HResult(IUnknown* self, ref Guid riid, void** result) QueryInterface;
                                                                                                      ^
ERROR: Member name expected at line 22:118 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] HResult(IUnknown* self, ref Guid riid, void** result) QueryInterface;
                                                                                                                     ^
ERROR: Expected type at line 23:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] uint32(IUnknown* self) AddRef;
                   ^
ERROR: Method return type expected at line 23:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] uint32(IUnknown* self) AddRef;
                                                 ^^^^^^
ERROR: Expected method body at line 23:72 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] uint32(IUnknown* self) AddRef;
                                                                       ^
ERROR: Member name expected at line 23:79 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] uint32(IUnknown* self) AddRef;
                                                                              ^
ERROR: Expected type at line 24:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] uint32(IUnknown* self) Release;
                   ^
ERROR: Method return type expected at line 24:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] uint32(IUnknown* self) Release;
                                                 ^^^^^^
ERROR: Expected method body at line 24:72 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] uint32(IUnknown* self) Release;
                                                                       ^
ERROR: Member name expected at line 24:80 in d:\3rdSrc\Beef\directx-beef\DirectX\src\Common\IUnknown.bf
   public function [CallingConvention(.Stdcall)] uint32(IUnknown* self) Release;
                                                                               ^
ERROR: Expected type at line 15:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Asynchronous.bf
   public function [CallingConvention(.Stdcall)] UINT(ID3D11Asynchronous *self) GetDataSize;
                   ^
ERROR: Method return type expected at line 15:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Asynchronous.bf
   public function [CallingConvention(.Stdcall)] UINT(ID3D11Asynchronous *self) GetDataSize;
                                                 ^^^^
ERROR: Expected method body at line 15:80 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Asynchronous.bf
   public function [CallingConvention(.Stdcall)] UINT(ID3D11Asynchronous *self) GetDataSize;
                                                                               ^
ERROR: Member name expected at line 15:92 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Asynchronous.bf
   public function [CallingConvention(.Stdcall)] UINT(ID3D11Asynchronous *self) GetDataSize;
                                                                                           ^
ERROR: Expected type at line 15:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11AuthenticatedChannel *self, UINT certificateSize, uint8 *pCertificate) GetCertificate;
                   ^
ERROR: Method return type expected at line 15:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11AuthenticatedChannel *self, UINT certificateSize, uint8 *pCertificate) GetCertificate;
                                                 ^^^^^^^
ERROR: Expected method body at line 15:134 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11AuthenticatedChannel *self, UINT certificateSize, uint8 *pCertificate) GetCertificate;
                                                                                                                                     ^
ERROR: Member name expected at line 15:149 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11AuthenticatedChannel *self, UINT certificateSize, uint8 *pCertificate) GetCertificate;
                                                                                                                                                    ^
ERROR: Expected type at line 16:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11AuthenticatedChannel *self, UINT *pCertificateSize) GetCertificateSize;
                   ^
ERROR: Method return type expected at line 16:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11AuthenticatedChannel *self, UINT *pCertificateSize) GetCertificateSize;
                                                 ^^^^^^^
ERROR: Expected method body at line 16:115 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11AuthenticatedChannel *self, UINT *pCertificateSize) GetCertificateSize;
                                                                                                                  ^
ERROR: Member name expected at line 16:134 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11AuthenticatedChannel *self, UINT *pCertificateSize) GetCertificateSize;
                                                                                                                                     ^
ERROR: Expected type at line 17:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11AuthenticatedChannel *self, Windows.Handle *pChannelHandle) GetChannelHandle;
                   ^
ERROR: Method return type expected at line 17:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11AuthenticatedChannel *self, Windows.Handle *pChannelHandle) GetChannelHandle;
                                                 ^^^^
ERROR: Expected method body at line 17:120 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11AuthenticatedChannel *self, Windows.Handle *pChannelHandle) GetChannelHandle;
                                                                                                                       ^
ERROR: Member name expected at line 17:137 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11AuthenticatedChannel.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11AuthenticatedChannel *self, Windows.Handle *pChannelHandle) GetChannelHandle;
                                                                                                                                        ^
ERROR: Expected type at line 15:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11BlendState.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11BlendState* self, BlendDescription *pDesc)GetDesc;
                   ^
ERROR: Method return type expected at line 15:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11BlendState.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11BlendState* self, BlendDescription *pDesc)GetDesc;
                                                 ^^^^
ERROR: Expected method body at line 15:103 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11BlendState.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11BlendState* self, BlendDescription *pDesc)GetDesc;
                                                                                                      ^
ERROR: Member name expected at line 15:110 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11BlendState.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11BlendState* self, BlendDescription *pDesc)GetDesc;
                                                                                                             ^
ERROR: Expected type at line 15:21 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Buffer.bf
    public function [CallingConvention(.Stdcall)] void(ID3D11Buffer* self, BufferDescription* desc) GetDesc;
                    ^
ERROR: Method return type expected at line 15:51 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Buffer.bf
    public function [CallingConvention(.Stdcall)] void(ID3D11Buffer* self, BufferDescription* desc) GetDesc;
                                                  ^^^^
ERROR: Expected method body at line 15:100 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Buffer.bf
    public function [CallingConvention(.Stdcall)] void(ID3D11Buffer* self, BufferDescription* desc) GetDesc;
                                                                                                   ^
ERROR: Member name expected at line 15:108 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Buffer.bf
    public function [CallingConvention(.Stdcall)] void(ID3D11Buffer* self, BufferDescription* desc) GetDesc;
                                                                                                           ^
ERROR: Expected type at line 16:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, ID3D11ClassLinkage **ppLinkage) GetClassLinkage;
                   ^
ERROR: Method return type expected at line 16:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, ID3D11ClassLinkage **ppLinkage) GetClassLinkage;
                                                 ^^^^
ERROR: Expected method body at line 16:114 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, ID3D11ClassLinkage **ppLinkage) GetClassLinkage;
                                                                                                                 ^
ERROR: Member name expected at line 16:130 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, ID3D11ClassLinkage **ppLinkage) GetClassLinkage;
                                                                                                                                 ^
ERROR: Expected type at line 17:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, ClassInstanceDescription *pDesc) GetDesc;
                   ^
ERROR: Method return type expected at line 17:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, ClassInstanceDescription *pDesc) GetDesc;
                                                 ^^^^
ERROR: Expected method body at line 17:115 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, ClassInstanceDescription *pDesc) GetDesc;
                                                                                                                  ^
ERROR: Member name expected at line 17:123 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, ClassInstanceDescription *pDesc) GetDesc;
                                                                                                                          ^
ERROR: Expected type at line 18:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, LPSTR pInstanceName, SIZE_T *pBufferLength) GetInstanceName;
                   ^
ERROR: Method return type expected at line 18:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, LPSTR pInstanceName, SIZE_T *pBufferLength) GetInstanceName;
                                                 ^^^^
ERROR: Expected method body at line 18:126 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, LPSTR pInstanceName, SIZE_T *pBufferLength) GetInstanceName;
                                                                                                                             ^
ERROR: Member name expected at line 18:142 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, LPSTR pInstanceName, SIZE_T *pBufferLength) GetInstanceName;
                                                                                                                                             ^
ERROR: Expected type at line 19:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, LPSTR pTypeName, SIZE_T *pBufferLength) GetTypeName;
                   ^
ERROR: Method return type expected at line 19:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, LPSTR pTypeName, SIZE_T *pBufferLength) GetTypeName;
                                                 ^^^^
ERROR: Expected method body at line 19:122 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, LPSTR pTypeName, SIZE_T *pBufferLength) GetTypeName;
                                                                                                                         ^
ERROR: Member name expected at line 19:134 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassInstance.bf
   public function [CallingConvention(.Stdcall)] void (ID3D11ClassInstance *self, LPSTR pTypeName, SIZE_T *pBufferLength) GetTypeName;
                                                                                                                                     ^
ERROR: Expected type at line 15:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassLinkage.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11ClassLinkage *self, char8 *pClassInstanceName, UINT instanceIndex, ID3D11ClassInstance **ppInstance) GetClassInstance;
                   ^
ERROR: Method return type expected at line 15:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassLinkage.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11ClassLinkage *self, char8 *pClassInstanceName, UINT instanceIndex, ID3D11ClassInstance **ppInstance) GetClassInstance;
                                                 ^^^^^^^
ERROR: Expected method body at line 15:164 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassLinkage.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11ClassLinkage *self, char8 *pClassInstanceName, UINT instanceIndex, ID3D11ClassInstance **ppInstance) GetClassInstance;
                                                                                                                                                                   ^
ERROR: Member name expected at line 15:181 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassLinkage.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11ClassLinkage *self, char8 *pClassInstanceName, UINT instanceIndex, ID3D11ClassInstance **ppInstance) GetClassInstance;
                                                                                                                                                                                    ^
ERROR: Expected type at line 16:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassLinkage.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11ClassLinkage *self, char8 *pClassTypeName, UINT constantBufferOffset, UINT constantVectorOffset, UINT textureOffset, UINT samplerOffset, ID3D11ClassInstance **ppInstance) CreateClassInstance;
                   ^
ERROR: Method return type expected at line 16:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassLinkage.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11ClassLinkage *self, char8 *pClassTypeName, UINT constantBufferOffset, UINT constantVectorOffset, UINT textureOffset, UINT samplerOffset, ID3D11ClassInstance **ppInstance) CreateClassInstance;
                                                 ^^^^^^^
ERROR: Expected method body at line 16:234 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassLinkage.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11ClassLinkage *self, char8 *pClassTypeName, UINT constantBufferOffset, UINT constantVectorOffset, UINT textureOffset, UINT samplerOffset, ID3D11ClassInstance **ppInstance) CreateClassInstance;
                                                                                                                                                                                                                                         ^
ERROR: Member name expected at line 16:254 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11ClassLinkage.bf
   public function [CallingConvention(.Stdcall)] HResult(ID3D11ClassLinkage *self, char8 *pClassTypeName, UINT constantBufferOffset, UINT constantVectorOffset, UINT textureOffset, UINT samplerOffset, ID3D11ClassInstance **ppInstance) CreateClassInstance;
                                                                                                                                                                                                                                                             ^
ERROR: Expected type at line 15:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CommandList.bf
   public function [CallingConvention(.Stdcall)] UINT(ID3D11CommandList *self) GetContextFlags;
                   ^
ERROR: Method return type expected at line 15:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CommandList.bf
   public function [CallingConvention(.Stdcall)] UINT(ID3D11CommandList *self) GetContextFlags;
                                                 ^^^^
ERROR: Expected method body at line 15:79 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CommandList.bf
   public function [CallingConvention(.Stdcall)] UINT(ID3D11CommandList *self) GetContextFlags;
                                                                              ^
ERROR: Member name expected at line 15:95 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CommandList.bf
   public function [CallingConvention(.Stdcall)] UINT(ID3D11CommandList *self) GetContextFlags;
                                                                                              ^
ERROR: Expected type at line 15:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Counter.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11Counter *self, CounterDescription *pDesc) GetDesc;
                   ^
ERROR: Method return type expected at line 15:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Counter.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11Counter *self, CounterDescription *pDesc) GetDesc;
                                                 ^^^^
ERROR: Expected method body at line 15:102 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Counter.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11Counter *self, CounterDescription *pDesc) GetDesc;
                                                                                                     ^
ERROR: Member name expected at line 15:110 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11Counter.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11Counter *self, CounterDescription *pDesc) GetDesc;
                                                                                                             ^
ERROR: Expected type at line 15:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, Guid *pCryptoType)GetCryptoType;
                   ^
ERROR: Method return type expected at line 15:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, Guid *pCryptoType)GetCryptoType;
                                                 ^^^^
ERROR: Expected method body at line 15:100 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, Guid *pCryptoType)GetCryptoType;
                                                                                                   ^
ERROR: Member name expected at line 15:113 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, Guid *pCryptoType)GetCryptoType;
                                                                                                                ^
ERROR: Expected type at line 16:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, Guid *pDecoderProfile)GetDecoderProfile;
                   ^
ERROR: Method return type expected at line 16:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, Guid *pDecoderProfile)GetDecoderProfile;
                                                 ^^^^
ERROR: Expected method body at line 16:104 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, Guid *pDecoderProfile)GetDecoderProfile;
                                                                                                       ^
ERROR: Member name expected at line 16:121 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, Guid *pDecoderProfile)GetDecoderProfile;
                                                                                                                        ^
ERROR: Expected type at line 17:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, UINT *pCertificateSize)GetCertificateSize;
                   ^
ERROR: Method return type expected at line 17:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, UINT *pCertificateSize)GetCertificateSize;
                                                 ^^^^
ERROR: Expected method body at line 17:105 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, UINT *pCertificateSize)GetCertificateSize;
                                                                                                        ^
ERROR: Member name expected at line 17:123 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, UINT *pCertificateSize)GetCertificateSize;
                                                                                                                          ^
ERROR: Expected type at line 18:20 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, UINT certificateSize, uint8 *pCertificate)GetCertificate;
                   ^
ERROR: Method return type expected at line 18:50 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, UINT certificateSize, uint8 *pCertificate)GetCertificate;
                                                 ^^^^
ERROR: Expected method body at line 18:124 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, UINT certificateSize, uint8 *pCertificate)GetCertificate;
                                                                                                                           ^
ERROR: Member name expected at line 18:138 in d:\3rdSrc\Beef\directx-beef\DirectX\src\D3D11\ID3D11CryptoSession.bf
   public function [CallingConvention(.Stdcall)] void(ID3D11CryptoSession *self, UINT certificateSize, uint8 *pCertificate)GetCertificate;
                                                                                                                                         ^
52 modules built, 1 object file generated
Errors: 1000. Only the first 100 are displayed.
Compile failed.

**Comment by sgf** [comment]
and Win64 Also a lot errors now.

**Comment by sgf** [comment]
got,should be use Beef-nightly version, tks
